Add Fastq transfer mode

diff --git a/src/ENAdumper b/src/ENAdumper
--- a/src/ENAdumper
+++ b/src/ENAdumper
@@ -5,7 +5,7 @@
 
 # Pre-set default settings
 set -eo pipefail
-version=0.1
+version=0.3
 mode="OFF"
 script=$(dirname -- "$BASH_SOURCE")
 config=$script/config.yaml
@@ -25,6 +25,7 @@ library_name=$(grep library_name $config | cut -d" " -f2 | tr -d '\r')
 library_source=$(grep library_source $config | cut -d" " -f2 | tr -d '\r')
 library_selection=$(grep library_selection $config | cut -d" " -f2 | tr -d '\r')
 library_strategy=$(grep library_strategy $config | cut -d" " -f2 | tr -d '\r')
+library_layout=$(grep library_layout $config | cut -d" " -f2 | tr -d '\r')
 
 # Usage instructions for terminal interface
 usage_text="
@@ -32,7 +33,7 @@ ENAdumper: a workflow for dumping sequencing data into ENA
 For issues or feedback please use https://github.com/Serka-M/ENAdumper/issues or mase@bio.aau.dk 
 
 COMPRESSION INPUTS:
--fq		--fastq_list		Path to list with FastQ files (default:$fastq)
+-fq		--fastq_list			Path to list with FastQ files (default:$fastq)
 -np		--fast5_dir			Path to directory with Fast5 files (default:$fast5)
 -n		--sample			Sample name (default:$sample)
 -p		--processes			Number of processes and fast5 batch count (default:$splits)
@@ -49,6 +50,7 @@ ENA METADATA INPUTS:
 -lib_src	--library_source		Library source category (default:$library_source)
 -lib_sel	--library_selection		Library selection category (default:$library_selection)
 -lib_strat	--library_strategy		Library strategy category (default:$library_strategy)
+-lib_lay	--library_layout		Library layout category (default:$library_layout)
 
 EXTRA INPUTS:
 -h		--help				Print help information
@@ -59,7 +61,7 @@ EXTRA INPUTS:
 while test $# -gt 0; do
            case "$1" in
                 -h | --help) printf -- "$usage_text"; exit 1;;
-                -v | --version) printf -- "ENAdumper version: $version\n"; exit 1;;
+                -v | --version) printf -- "ENAdumper, v$version\n"; exit 1;;
                 -np | --fast5_dir) shift; fast5=$1 && mode="fast5" && snakefile=$script/snake_np; shift;;
                 -fq | --fastq_list) shift; fastq=$1 && mode="fastq" && snakefile=$script/snake_fq; shift;;
                 -n | --sample) shift; sample=$1; shift;;
@@ -67,7 +69,7 @@ while test $# -gt 0; do
                 -k | --key) shift; key=$1; shift;;
                 -user | --webin_user) shift; webin_user=$1; shift;;
                 -pass | --webin_pass) shift; webin_pass=$1; shift;;
-                -p | --processes) shift splits=$1; if [ $splits -gt 9 ]; then splits=9; fi; shift;;
+                -p | --processes) shift; splits=$1; shift;;
                 -ins | --instrument_model) shift; instrument_model=$1; shift;;
                 -lib_n | --library_name) shift; library_name=$1; shift;;
                 -lib_src | --library_source) shift; library_source=$1; shift;;
@@ -118,6 +120,7 @@ if ! command -v xargs &> /dev/null; then echo "Depedency "xargs" could not be fo
 if ! command -v tar &> /dev/null; then echo "Depedency tar "could" not be found. Aborting..." && exit 1; fi
 if ! command -v md5sum &> /dev/null; then echo "Depedency "md5sum" could not be found. Aborting..." && exit 1; fi
 if ! command -v ascp &> /dev/null; then echo "Depedency "ascp" could not be found. Aborting..." && exit 1; fi
+if ! command -v basename &> /dev/null; then echo "Depedency "basename" could not be found. Aborting..." && exit 1; fi
 
 # Make directory for output
 if [ ! -d "$(pwd)/ENAdumper_${mode}_${sample}" ]; then mkdir $(pwd)/ENAdumper_${mode}_${sample}; fi
@@ -125,6 +128,6 @@ if [ ! -d "$(pwd)/ENAdumper_${mode}_${sample}" ]; then mkdir $(pwd)/ENAdumper_${
 # Run snakemake workflow
 echo "Starting Snakemake workflow for uploading $mode files..."
 cd $(pwd)/ENAdumper_${mode}_${sample}
-snakemake --cores $splits -s $snakefile --configfile $config --config sample=$sample study=$study fast5=$fast5 fastq=$fastq splits=$splits webin_pass=$webin_pass webin_user=$webin_user key=$key instrument_model=$instrument_model library_name=$library_name library_source=$library_source library_selection=$library_selection library_strategy=$library_strategy
+snakemake --cores $splits -s $snakefile --configfile $config --config sample=$sample study=$study fast5=$fast5 fastq=$fastq splits=$splits webin_pass=$webin_pass webin_user=$webin_user key=$key instrument_model=$instrument_model library_name=$library_name library_source=$library_source library_selection=$library_selection library_strategy=$library_strategy library_layout=$library_layout
 cd ..
 exit 0
