Add files via upload

diff --git a/src/ENAdumper b/src/ENAdumper
--- a/src/ENAdumper
+++ b/src/ENAdumper
@@ -12,6 +12,7 @@ config=$script/config.yaml
 
 splits=$(grep splits $config | cut -d" " -f2 | tr -d '\r')
 fast5=$(grep fast5 $config | cut -d" " -f2 | tr -d '\r')
+fastq=$(grep fastq $config | cut -d" " -f2 | tr -d '\r')
 sample=$(grep sample $config | cut -d" " -f2 | tr -d '\r')
 
 webin_user=$(grep webin_user $config | cut -d" " -f2 | tr -d '\r')
@@ -31,7 +32,7 @@ ENAdumper: a workflow for dumping sequencing data into ENA
 For issues or feedback please use https://github.com/Serka-M/ENAdumper/issues or mase@bio.aau.dk 
 
 COMPRESSION INPUTS:
--fq		--fastq_dir			Path to directory with FastQ files (default:$fastq)
+-fq		--fastq_list		Path to list with FastQ files (default:$fastq)
 -np		--fast5_dir			Path to directory with Fast5 files (default:$fast5)
 -n		--sample			Sample name (default:$sample)
 -p		--processes			Number of processes and fast5 batch count (default:$splits)
@@ -60,7 +61,7 @@ while test $# -gt 0; do
                 -h | --help) printf -- "$usage_text"; exit 1;;
                 -v | --version) printf -- "ENAdumper version: $version\n"; exit 1;;
                 -np | --fast5_dir) shift; fast5=$1 && mode="fast5" && snakefile=$script/snake_np; shift;;
-                -fq | --fastq_dir) shift; fastq=$1 && mode="fastq" && snakefile=$script/snake_fq; shift;;
+                -fq | --fastq_list) shift; fastq=$1 && mode="fastq" && snakefile=$script/snake_fq; shift;;
                 -n | --sample) shift; sample=$1; shift;;
                 -s | --study) shift; study=$1; shift;;
                 -k | --key) shift; key=$1; shift;;
@@ -90,6 +91,13 @@ if [[ ! "$fast5" = /* ]]; then fast5="$(pwd)/$fast5"; fi
 # Check if fast5 input directory exists
 if [ ! -d "$fast5" ]; then echo "ERROR: fast5 directory not found at $fast5. Aborting..." && exit 1; fi; fi
 
+# Checks for fastq transfer mode
+if [ $mode == "fastq" ]; then
+# Turn relative path into absolute for fastq input
+if [[ ! "$fastq" = /* ]]; then fastq="$(pwd)/$fastq"; fi
+# Check if fastq input directory exists
+if [ ! -f "$fastq" ]; then echo "ERROR: fastq list file not found at $fastq. Aborting..." && exit 1; fi; fi
+
 # Turn relative path into absolute for key file
 if [[ ! "$key" = /* ]]; then key="$(pwd)/$key"; fi
 
@@ -115,8 +123,8 @@ if ! command -v ascp &> /dev/null; then echo "Depedency "ascp" could not be foun
 if [ ! -d "$(pwd)/ENAdumper_${mode}_${sample}" ]; then mkdir $(pwd)/ENAdumper_${mode}_${sample}; fi
 
 # Run snakemake workflow
-echo "Starting snakemake workflow in $mode mode..."
+echo "Starting Snakemake workflow for uploading $mode files..."
 cd $(pwd)/ENAdumper_${mode}_${sample}
-snakemake --cores 1 -s $snakefile --configfile $config --config sample=$sample study=$study fast5=$fast5 splits=$splits webin_pass=$webin_pass webin_user=$webin_user key=$key instrument_model=$instrument_model library_name=$library_name library_source=$library_source library_selection=$library_selection library_strategy=$library_strategy
+snakemake --cores $splits -s $snakefile --configfile $config --config sample=$sample study=$study fast5=$fast5 fastq=$fastq splits=$splits webin_pass=$webin_pass webin_user=$webin_user key=$key instrument_model=$instrument_model library_name=$library_name library_source=$library_source library_selection=$library_selection library_strategy=$library_strategy
 cd ..
 exit 0
diff --git a/src/snake_np b/src/snake_np
--- a/src/snake_np
+++ b/src/snake_np
@@ -18,67 +18,62 @@ library_selection=config["library_selection"]
 library_strategy=config["library_strategy"]
 
 rule all:
+    input:
+        expand("ENA_{name}.tsv", name=sample)
     message:
         "End of workflow. Please submit ENA_{sample}.tsv to ENA to have your data included in the permanent archive."
-    input:
-        'split.txt',
-        'compress.txt',
-        'upload.txt',
-        'document.txt'
 
 rule split:
-    priority: 4
     params:
         find='-name "*.fast5"'
     output:
-        out='split.txt'
+        expand("{name}_fast5.txt", name=sample)
     shell:
         """
-        find {fast5} {params.find} > fast5_{sample}.txt
-        split -n l/{splits} --numeric-suffixes=1 -d fast5_{sample}.txt {sample}_fast5_
-        echo "Fast5 splitting completed at $(date "+%Y-%m-%d %H:%M:%S")" > {output.out}
+        find {fast5} {params.find} > {output}
+        split -n l/{splits} --numeric-suffixes=1 -d {output} {sample}_fast5_
         """
 
 rule compress:
-    priority: 3
+    input:
+        expand("{name}_fast5.txt", name=sample)
     output:
-        out='compress.txt'
+        expand("{name}_fast5_01.tar.gz", name=sample)
     shell:
         """
         find {sample}_fast5_[0-9][0-9] | xargs -i --max-procs={splits} bash -c "tar -cvzf {{}}.tar.gz -T {{}}"
         find {sample}_fast5_[0-9][0-9].tar.gz | xargs -i --max-procs={splits} bash -c "md5sum {{}} > {{}}.md5"
-        echo "Fast5 compression completed at $(date "+%Y-%m-%d %H:%M:%S")" > {output.out}
+        if [ ! -f {output} ]; then printf "Error with fast5 compression" && exit 1; fi
         """
 
 rule upload:
-    priority: 2
+    input:
+        expand("{name}_fast5_01.tar.gz", name=sample)
     output:
-        out='upload.txt'
+        'upload.txt'
     shell:
         """
-	export ASPERA_SCP_PASS={webin_pass}
+        export ASPERA_SCP_PASS={webin_pass}
         find {sample}_fast5_[0-9][0-9].tar.gz | xargs -i --max-procs={splits} bash -c "ascp -QT -l300M -L- {{}} {webin_user}@webin.ebi.ac.uk:."
-        echo "Fast5 upload to ENA completed at $(date "+%Y-%m-%d %H:%M:%S")" > {output.out}
+        printf "Fast5 upload to ENA completed at $(date "+%Y-%m-%d %H:%M:%S")\n" > {output}
         """
 
 rule document:
-    priority: 1
+    input:
+        'upload.txt'
     output:
-        out='document.txt'
+        expand("ENA_{name}.tsv", name=sample)
     shell:
         """
-	sample_ena=$(grep {sample} {key} | cut -f2)
-	library={library_name}{sample}
+        sample_ena=$(grep {sample} {key} | cut -f2)
+        library={library_name}{sample}
 
-	printf "FileType\tOxfordNanopore_native\tRead submission file type\n" > ENA_{sample}.tsv
-	printf "sample\tstudy\tinstrument_model\tlibrary_name\tlibrary_source\tlibrary_selection\tlibrary_strategy\tfile_name\tfile_md5\n" >> ENA_{sample}.tsv
+        printf "FileType\tOxfordNanopore_native\tRead submission file type\n" > {output}
+        printf "sample\tstudy\tinstrument_model\tlibrary_name\tlibrary_source\tlibrary_selection\tlibrary_strategy\tfile_name\tfile_md5\n" >> {output}
 
-	for file in {sample}_fast5_[0-9][0-9].tar.gz; do
+        for file in {sample}_fast5_[0-9][0-9].tar.gz; do
 		md5=$(cat $file.md5 | sed 's/  /,/' | cut -f1 -d",")
 		file_name=$(cat $file.md5 | sed 's/  /,/' | cut -f2 -d",")
-		printf "$sample_ena\t{study}\t{instrument_model}\t$library\t{library_source}\t{library_selection}\t{library_strategy}\t$file_name\t$md5\n" >> ENA_{sample}.tsv
-	done
-
-        echo "Fast5 data sheet generation completed at $(date "+%Y-%m-%d %H:%M:%S")" > {output.out}
+		printf "$sample_ena\t{study}\t{instrument_model}\t$library\t{library_source}\t{library_selection}\t{library_strategy}\t$file_name\t$md5\n" >> {output}
+        done
         """
-
